KS-4-5 solving the problem about the ship
ssbykov/KotlinSprint pull request #20
Opened 2023-11-09 19:39 UTC by ssbykov

2023-11-11 06:43 UTC, ievetrov requested changes

2023-11-11 06:43 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +        (!isDamage && numberOfCrew in (MIN_TEAM_MEMBER..MAX_TEAM_MEMBER)
все супер! только небольшой косяк с условием) в первом случае нам погода не важна, поэтому `isWeather` можно удалить. во втором условии сейчас у тебя корабль может полететь только если имеет повреждения, давай это тоже удалим

2023-11-11 06:43 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val approved =
эта переменная булеан, давай ее тоже назовем с is или has

2023-11-11 09:22 UTC, ssbykov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +        (!isDamage && numberOfCrew in (MIN_TEAM_MEMBER..MAX_TEAM_MEMBER)
мда... какие-то детские ошибки )

2023-11-12 06:11 UTC, ievetrov requested changes

2023-11-12 06:11 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val quantityOfProvisions = readLine()!!.toInt()
использование `!!` в коде является плохой практикой, так как в случае получения значения null наша программа упадет. вместо этого стоит проверять как в способе выше `readlnOrNull()?.toInt()`)

2023-11-12 08:07 UTC, ssbykov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val quantityOfProvisions = readLine()!!.toInt()
Но ведь при использовании readlnOrNull()?.toInt(), при пустой строке тоже вылетает ошибка NumberFormatException. В чем тогда смысл?

2023-11-13 06:18 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val quantityOfProvisions = readLine()!!.toInt()
такие приведения типов в любом случае предполагают обработку возможных ошибок (дальше по курсу будем проходить эту тему). но когда мы сами обрабатываем ошибку в дальнейшем мы можем легко понять в каком месте программы она происходит, в отличие от варианта с `!!`

2023-11-13 06:18 UTC, ievetrov approved these changes

2023-11-13 09:53 UTC, merged