KS-1-3 wrote a solution to problem 3
ssbykov/KotlinSprint pull request #3
Opened 2023-11-06 09:27 UTC by ssbykov

2023-11-06 15:55 UTC, ievetrov requested changes
оставил коммент для доработки. нужно будет закоммитить и запушить изменения в эту ветку и прислать снова ссылку на данный пулл реквест в бот к соответствующей задаче

2023-11-06 15:55 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +    var hour = 9
В целом результат есть! но в примере в ТЗ цифры начинаются с 0.
Вообще нормальная практика, если сервер присылает дату или время строкой.
Давай объявим строки и сделаем правильный формат)

2023-11-06 16:06 UTC, ssbykov commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +    var hour = 9
Уточните. Текстом приходит и время взлета и время посадки? То есть сначала получаем строку " 09:07", потом "10:55"?

2023-11-07 06:32 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_3.kt
> +    var hour = 9
да

2023-11-07 10:28 UTC, ievetrov approved these changes
получилось более продвинуто, оч хорошо)

2023-11-07 11:00 UTC, merged